server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://106.15.204.107:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

missyou:
  security:
    jwt-key: hahaha
    token-expired-in: 86400000